sudo: false
language: r
cache: packages
warnings_are_errors: false

# whitelist
branches:
  only:
    - master

after_success:
  - Rscript -e 'covr::codecov(type = "all", commentDontrun = FALSE, commentDonttest = FALSE)'
