// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ccc_rcpp
Rcpp::IntegerVector ccc_rcpp(std::vector<std::string>& dx, std::vector<std::string>& pc, int version);
RcppExport SEXP pccc_ccc_rcpp(SEXP dxSEXP, SEXP pcSEXP, SEXP versionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string>& >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string>& >::type pc(pcSEXP);
    Rcpp::traits::input_parameter< int >::type version(versionSEXP);
    rcpp_result_gen = Rcpp::wrap(ccc_rcpp(dx, pc, version));
    return rcpp_result_gen;
END_RCPP
}
// ccc_mat_rcpp
Rcpp::IntegerMatrix ccc_mat_rcpp(Rcpp::CharacterMatrix& dx, Rcpp::CharacterMatrix& pc, int version);
RcppExport SEXP pccc_ccc_mat_rcpp(SEXP dxSEXP, SEXP pcSEXP, SEXP versionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterMatrix& >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterMatrix& >::type pc(pcSEXP);
    Rcpp::traits::input_parameter< int >::type version(versionSEXP);
    rcpp_result_gen = Rcpp::wrap(ccc_mat_rcpp(dx, pc, version));
    return rcpp_result_gen;
END_RCPP
}
// get_codes
Rcpp::List get_codes(int icdv);
RcppExport SEXP pccc_get_codes(SEXP icdvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type icdv(icdvSEXP);
    rcpp_result_gen = Rcpp::wrap(get_codes(icdv));
    return rcpp_result_gen;
END_RCPP
}
