// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dx_codes
Rcpp::List dx_codes(int version);
RcppExport SEXP pccc_dx_codes(SEXP versionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type version(versionSEXP);
    rcpp_result_gen = Rcpp::wrap(dx_codes(version));
    return rcpp_result_gen;
END_RCPP
}
// pc_codes
Rcpp::List pc_codes(int version);
RcppExport SEXP pccc_pc_codes(SEXP versionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type version(versionSEXP);
    rcpp_result_gen = Rcpp::wrap(pc_codes(version));
    return rcpp_result_gen;
END_RCPP
}
// dx_nuromusc
Rcpp::StringVector dx_nuromusc(int version);
RcppExport SEXP pccc_dx_nuromusc(SEXP versionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type version(versionSEXP);
    rcpp_result_gen = Rcpp::wrap(dx_nuromusc(version));
    return rcpp_result_gen;
END_RCPP
}
