# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

code_test <- function(version) {
    .Call('pccc_code_test', PACKAGE = 'pccc', version)
}

dx_codes <- function(version) {
    .Call('pccc_dx_codes', PACKAGE = 'pccc', version)
}

pc_codes <- function(version) {
    .Call('pccc_pc_codes', PACKAGE = 'pccc', version)
}

dx_nuromusc <- function(version) {
    .Call('pccc_dx_nuromusc', PACKAGE = 'pccc', version)
}

