# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_codes <- function(version = 9L) {
    .Call('pccc_get_codes', PACKAGE = 'pccc', version)
}

ccc_rcpp <- function(dx, pc, version = 9L) {
    .Call('pccc_ccc_rcpp', PACKAGE = 'pccc', dx, pc, version)
}

